### ISSUE TITLE
wflogger.py unsupported operand types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wfrog/wfrog#104]
```
What steps will reproduce the problem?
1. Start wflogger

What is the expected output? What do you see instead?
Expected events to be logged to wfrog.csv

What happens instead: nothing logged to wfrog.csv. 
wflogger.log is full of same error:

2012-02-07 19:26:22,431 ERROR [wflogger] Could not send event to 
<wfcommon.generic.YamlMultiElement object at 0x40d33a30>
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/wflogger.py", line 127, in output_loop
    self.collector.send_event(event, context=context)
  File "/share/MD0_DATA/.qpkg/wfrog/wfcommon/generic/multi.py", line 62, in _call
    result[name] = r.__getattribute__(attr).__call__(*args, **keywords)
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/buffer.py", line 99, in send_event
    self.forward_event(event_to_send, context)
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/buffer.py", line 133, in forward_event
    self.do_send(flush_event, context)
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/buffer.py", line 139, in do_send
    self.collector.send_event(event, context)
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/base.py", line 47, in send_event
    self.flush(context)
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/aggregator.py", line 179, in flush
    sample = self.get_data()
  File "/share/MD0_DATA/.qpkg/wfrog/wflogger/collector/aggregator.py", line 123, in get_data
    data['temp'] = round(sum(self._temp)/len(self._temp), 1)
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'


What version of the product are you using? On what operating system?
wfrog: 0.8.1
OS: QNAP TS-209
Station: Fine Offset WH3081
driver: wh1080

Please provide any additional information below.

```

Original issue reported on code.google.com by `warren.c...@gmail.com` on 7 Feb 2012 at 8:40

**Comment by karsta62** [comment]
I have the same issue right now. Same log messages. Started recently. Don't remember making any changes.
Raspberry Pi 1, raspbian wheezy wfrog 0.8.2 wh1080.

wfrog-current.xml updates fine, wfrog.csv started having several hour breaks until back working. Now have been 34 hours dead. Several power resets done for console and raspi. Does not recover anymore.

**Comment by karsta62** [comment]
After my last message it finally started working quite well by itself, but now back in square one. I'm still having this. wfrog stops writing to wfrog.csv but wfrog-current.xml updates normally. No changes made.
Occasionally it works a while, but then stops. No clue what's happening. Same thing in two different environments. Both having WH1080 though. 
I shrinked the wfrog.csv to have only two years of data, but it does not help at all.
Probably must get some other application.

**Comment by karsta62** [comment]
I got one instance (raspi) fixed according to this (_hum / _temp bug):
https://groups.google.com/forum/#!topic/wfrog-users/KZGc7LozDNo
The other instance (ubuntu) has very different aggregator.py so does not fix that.
